In [1]:
import numpy as np # numpy ı np diye tanımladık.
np.array([1,2,5])

array([1, 2, 5])

In [2]:
dizi=np.array([1,3,5,8,11])
dizi

array([ 1,  3,  5,  8, 11])

In [3]:
dizi=np.array([1,2,3,3.14],dtype=int)
dizi


array([1, 2, 3, 3])

In [4]:
birboyut=np.array([1,2,3,])
birboyut

array([1, 2, 3])

In [7]:
ikiboyut=np.array ([[1,2,3,],[4,5,6]])
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [13]:
np.ones((4,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.full((4,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [17]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.random.randint(0,10,5)

array([3, 3, 3, 7, 9])

In [19]:
np.random.randint(0,10,(4,3))

array([[7, 3, 3],
       [9, 7, 9],
       [0, 4, 2],
       [2, 6, 4]])