In [1]:
import numpy as np #numpy Kütüpahenesini np değişkenineni atadık 


In [20]:
dizi=np.full((4,3),5) # full metodu sütunları ve satırları oluşturur.4 satır 3 sütun içindede 5 değeri olsun.
dizi


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# b ye basınca yeni satır ekler alt tarafa...

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
dizi=np.array(["elma","erik","iğde"]) #diziyi "dizi" adında bir değişkene atadık.
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [7]:
dizi=np.array([1,2,3])

In [8]:
dizi=np.array([1,2,3.14])

In [10]:
dizi.dtype #dizinin değişken türünü verir.numpy dizelerede elemanların hepsi aynı türdedir.

dtype('float64')

In [15]:
dizi=np.array([1,2,3.14],dtype=int)
dizi

array([1, 2, 3])

In [17]:
birboyut=np.array([1,2,3,4]) #bir boyutlu dizenin oluşumu
birboyut

array([1, 2, 3, 4])

In [19]:
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #iki boyutlu dizenin oluşumu.
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np.zeros(7)#zeros etiketi dizeye otomatik olarak 0 değerini veriri parantez içinde hangi sayıyı yazarsanız 7 tane değer ekler.

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,3),dtype=int),


array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.full((4,3,),5)


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [27]:
np.arange(2,22,5)

array([ 2,  7, 12, 17])

In [28]:
np.linspace(2,10,num=7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [29]:
np.random.randint(0,10,5)

array([2, 9, 3, 2, 4])

In [30]:
np.random.randint(0,10,(5,2))

array([[0, 0],
       [3, 6],
       [0, 9],
       [4, 9],
       [4, 4]])

In [31]:
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [32]:
dizi.ndim

2

In [33]:
dizi.size

12

In [35]:
dizi.itemsize

4